version: '2.15'

services:

  db:
    image: mysql
    environment:
      MYSQL_DATABASE: 'school_db'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    networks:
      school:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev"
    networks:
      school:

  config-server:
    image: school/configserver
    ports:
      - "8888:8888"
    networks:
      school:

  eureka-server:
    image: school/eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      school:

networks:
  school: