version: '2.15'

services:

  config-server:
    image: school/configserver
    ports:
      - "8888:8888"
    networks:
      school:

  eureka-server:
    image: school/eureka-server
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    networks:
      school:

networks:
  school: